# Changes here will be overwritten by Copier
_commit: dcfbd4b
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: cpp
add_pyodide: true
add_vcpkg: true
add_wiki: true
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A C++-Python project template
project_name: python template cpp
python_version_primary: '3.11'
team: Python Project Template Authors
